version: '3.9'

services:
  user_microservice:
    container_name: users_microservice
    restart: always
    build: .
    image: users-ms
    ports:
      - "5000:5151"
    networks:
      - red-externa
networks:
  red-externa:
    name: frame_net
    external: true

